### ISSUE TITLE
Tests fail on most systems

### ISSUE THREAD

**Issue by eserte** [xtaran/CGI-Github-Webhook#1]
See http://matrix.cpantesters.org/?dist=CGI-Github-Webhook%200.04 for an overview of reports.

One problem seems to be that somewhere in the test suite it's assumed that the first perl in `PATH` is the same perl used for the test, which is not always the case. Typically this can be fixed by using `$^X`.

There seems to be another problem on freebsd systems --- tests fail even if the perl in `PATH` and the perl used for the test is the same.

**Comment by xtaran** [comment]
Hi Slaven,

On Wed, Jun 29, 2016 at 11:34:40PM -0700, Slaven Rezić wrote:

> Tests fail on most systems

Yes, I'm fully aware of it and I so far had no real idea. I've posted
it as question on StackOverflow at
https://stackoverflow.com/questions/37769679/smoke-tests-fail-for-most-cpantesters-but-work-fine-on-travis-ci-and-locally-un
but the only answer so far seems to fix an unrelated issue. (Feel free
to answer it there, too, to get some reputation points there. :-)

> One problem seems to be that somewhere in the test suite it's
> assumed that the first perl in `PATH` is the same perl used for the
> test, which is not always the case.

Ok. Indeed, I'm aware that /usr/bin/perl is not always the first in
the path and replaced it in the test suite with "#!/usr/bin/env perl"
after test suite failures on DragonflyBSD which has no more
/usr/bin/perl (but only /usr/local/bin/perl IIRC). But as it seems
this is not the best solution either and using CGI::Test seem to have
brought the remaining issues to the foreground.

> Typically this can be fixed by using `$^X`.

Hrm. But I can't use $^X in the shebang line, so I need to use that in
the calling script... Will have a look.

Thanks a lot for the analysis!

> There seems to be another problem on freebsd systems --- tests fail
> even if the perl in `PATH` and the perl used for the test is the
> same.

Haven't looked at that yet as I was still gnawing on the general path
issue. Will probably solve the path issue first, do an upload and see
what improves and what not.

```
    Kind regards, Axel
```

## 

/~\  Plain Text Ribbon Campaign                   | Axel Beckert
\ /  Say No to HTML in E-Mail and News            | abe@deuxchevaux.org  (Mail)
 X   See http://www.nonhtmlmail.org/campaign.html | abe@noone.org (Mail+Jabber)
/ \  I love long mails: http://email.is-not-s.ms/ | http://abe.noone.org/ (Web)

**Comment by xtaran** [comment]
As far as I can see, CGI::Test already sets `$ENV{PERL} = $^X;` in its `_run_cgi` method and since that's the place where I'd expected it, I currently wonder where else it might be missing. Hints welcome!

**Comment by xtaran** [comment]
Ok, I seem to have it working with this very ugly hack:

``` diff
diff --git a/t/cgi/cgitest.pl b/t/cgi/cgitest.pl
index 4044cb6..c77c816 100755
--- a/t/cgi/cgitest.pl
+++ b/t/cgi/cgitest.pl
@@ -3,11 +3,17 @@
 use strict;
 use warnings;
 use 5.010;
+use File::Basename;
+
+if (defined $ENV{PERL} and $ENV{PERL} ne $^X) {
+    my $dir = dirname($0);
+    exec '/usr/bin/env', "PERL5LIB=$ENV{PERL5LIB}:$dir/../../lib:$dir/../../blib", $ENV{PERL}, $0;
+}

 #use CGI;
 #my $cgi = CGI->new();

-use CGI::Github::Webhook;
+require CGI::Github::Webhook;

 my $ghwh = CGI::Github::Webhook->new(
     trigger => 'echo foo',
```

Can't believe that such hackery is necessary just to use CGI::Test…

@eserte: Do you know a better way to tackle this?

**Comment by xtaran** [comment]
Meh. Of course that won't work on any DOS-ish platform.
