### ISSUE TITLE
Race condition in test suite (0.05)

### ISSUE THREAD

**Issue by eserte** [xtaran/CGI-Github-Webhook#2]
0.05 now passes on my linux smokers, but still fails on the freebsd ones. Looking at the truss log while running t/cgi-test-auth-fail.t it seems that there's a race condition:

```
64932: 0.115133907 0.000014527 open("/dev/stdout",O_WRONLY|O_APPEND|O_CREAT,0666) = 3 (0x3)
...
64932: 0.115357399 0.000010057 open("/dev/stdout",O_WRONLY|O_APPEND|O_CREAT,0666) = 4 (0x4)
...
64932: 0.130372156 0.000086324 write(4,"Date: Fri Jul  1 23:09:19 2016\nRemote IP: localhost (127.0.0.1)\n$VAR1 = {\n          'payload' => 'none'\n        };\n$VAR2 = '<no-x-hub-signature>';\n$VAR3 = 'sha1=78f444a9b7282e9e1ae0f520044e8d9b52243ec9';\n",204) = 204 (0xcc)
...
64932: 0.130554861 0.000015365 write(3,"Authentication failed\n",22) = 22 (0x16)
...
64932: 0.134588335 0.000006146 write(1,"Content-Type: text/plain; charset=utf-8\r\n\r\nAuthentication failed\n",65) = 0 (0x0)
```

So the header gets written after the body. In fact, if log in t/cgi/cgitest.pl is set to `/dev/stderr` instead of `/dev/stdout`, then the test passes (although now the debugging output is visible in the test suite).

**Comment by xtaran** [comment]
Thanks for the detailed analysis. Will have a look.

**Comment by xtaran** [comment]
@eserte: Hrm, do you think that something like `local $| = 1;` inside `CGI::Github::Webhook::run()` could help?

**Comment by eserte** [comment]
`local $| = 1` on top of the run() method helps.

**Comment by xtaran** [comment]
Thanks for testing!
